spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: characters
      auto-index-creation: false

mongodb:
  uri: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/