version: '3'

services:

  app:
    container_name: "soap_client"
    hostname: localhost
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
      - "8000:8000"     # debugging
