server:
  port: 8083

application:
  developer: Nizami Islamovs
  version: v 1.0.0
  deploymentdate: 2018-09-11 21:15:29
  support.email: nizamiislamovs@gmail.com
  description: SOAP client mcs
  title: SOAP client mcs


logging.level.org.springframework.ws.client.MessageTracing.sent: TRACE
logging.level.org.springframework.ws.client.MessageTracing.received: TRACE
logging.level.org.springframework.ws: TRACE
logging.level.com.soap.soapclient: TRACE

client:
  ssl:
    keyStore: classpath:clientWs.p12
    keyStorePassword: password
    keyPassword: password
    trustStore: classpath:truststore.jks
    trustStorePassword: password

client.soap.ws.pathPrefix: /api/v1/ws
client.soap.ws.targetNamespace: https://localhost:8443${client.soap.ws.pathPrefix}