server:
  port: 8083

application:
  developer: Nizami Islamovs
  version: v 1.0.0
  deploymentdate: 2018-09-11 21:15:29
  support.email: nizamiislamovs@gmail.com
  description: SOAP client mcs
  title: SOAP client mcs


logging:
  level:
    com.soap.soapclient: INFO
    org:
      springframework:
        ws: DEBUG